# Generated by Django 3.1.4 on 2021-01-02 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deadline_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(default=None)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('answer_text', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision.question')),
            ],
        ),
    ]
